# Pandas Playground

In [1]:
import pandas as pd

**1.** Create a DataFrame `df` from this dictionary `data` which has the index `labels`.

In [2]:
import numpy as np

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data, index=labels)
df

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

**2.** Display a summary of the basic information about this DataFrame and its data (*hint: there is a single method that can be called on the DataFrame*).

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   animal    10 non-null     object
 1   age       8 non-null      float64
 2   visits    10 non-null     int64
 3   priority  10 non-null     object
dtypes: float64(1), int64(1), object(2)
memory usage: 700.0+ bytes

**3.** Return the first 3 rows of the DataFrame `df`.

In [4]:
df.iloc[0:3]

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

**4.** Select just the 'animal' and 'age' columns from the DataFrame `df`.

In [5]:
df[['animal','age']]

  animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

**5.** Select the data in rows `[3, 4, 8]` *and* in columns `['animal', 'age']`.

In [6]:
df.loc[df.index[[3,4,8]],['animal', 'age']]

  animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0

**6.** Select only the rows where the number of visits is greater than 3.

In [7]:
df.loc[df['visits']>3]

Empty DataFrame
Columns: [animal, age, visits, priority]
Index: []

**7.** Select the rows where the age is missing, i.e. it is `NaN`.

In [8]:
df[df['age'].isnull()]

  animal  age  visits priority
d    dog  NaN       3      yes
h    cat  NaN       1      yes

**8.** Select the rows where the animal is a cat *and* the age is less than 3.

In [9]:
df[(df['animal']=='cat') & (df["age"]<3)]

  animal  age  visits priority
a    cat  2.5       1      yes
f    cat  2.0       3       no

**9.** Change the age in row 'f' to 1.5.

In [10]:
df.loc["f","age"] = 1.5
df

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

**10.** Calculate the sum of all visits in `df` (i.e. find the total number of visits).

In [11]:
df["visits"].sum()

np.int64(19)

**11.** Calculate the mean age for each different animal in `df`.

In [12]:
df.groupby("animal")["age"].mean()

animal
cat      2.333333
dog      5.000000
snake    2.500000
Name: age, dtype: float64

**12.** Count the number of each type of animal in `df`.

In [13]:
df["animal"].value_counts()

animal
cat      4
dog      4
snake    2
Name: count, dtype: int64

**13.** Sort `df` first by the values in the 'age' in *decending* order, then by the value in the 'visits' column in *ascending* order (so row `i` should be first, and row `d` should be last).

In [14]:
df.sort_values(by=["age","visits"], ascending=[False,True])

  animal  age  visits priority
i    dog  7.0       2       no
e    dog  5.0       2       no
g  snake  4.5       1       no
j    dog  3.0       1       no
b    cat  3.0       3      yes
a    cat  2.5       1      yes
f    cat  1.5       3       no
c  snake  0.5       2       no
h    cat  NaN       1      yes
d    dog  NaN       3      yes

**14.** The 'priority' column contains the values 'yes' and 'no'. Replace this column with a column of boolean values: 'yes' should be `True` and 'no' should be `False`.

In [15]:
df["priority"]=df["priority"].map({"yes": True, "no": False})

**15.** In the 'animal' column, change the 'snake' entries to 'python'.

In [16]:
df['animal'] = df["animal"].replace("snake","python")

**16** Create a new column called 'info' by applying a function row-wise (axis=1) that:

Joins the 'animal' and 'priority' columns like this: "{animal} ({priority})".

If 'priority' is 'yes', capitalize the whole result. Otherwise, leave it lowercase.

In [17]:
def create_info(row):
    result = f"{row['animal']} ({row['priority']})"
    if row['priority'] == 'yes':
        return result.upper()
    else:
        return result.lower()

df['info'] = df.apply(create_info, axis=1)
df

   animal  age  visits  priority            info
a     cat  2.5       1      True      cat (true)
b     cat  3.0       3      True      cat (true)
c  python  0.5       2     False  python (false)
d     dog  NaN       3      True      dog (true)
e     dog  5.0       2     False     dog (false)
f     cat  1.5       3     False     cat (false)
g  python  4.5       1     False  python (false)
h     cat  NaN       1      True      cat (true)
i     dog  7.0       2     False     dog (false)
j     dog  3.0       1     False     dog (false)

**16.** You have a DataFrame `df` with a column 'A' of integers. For example:
```python
df = pd.DataFrame({'A': [1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 7]})
```

How do you filter out rows which contain the same integer as the row immediately above?

You should be left with a column containing the following values:

```python
1, 2, 3, 4, 5, 6, 7
```

In [27]:
df = pd.DataFrame({'A': [1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 7]})
df.loc[df["A"]!=df["A"].shift()]

   A
0  1
1  2
3  3
4  4
5  5
8  6
9  7

**17.** Given a DataFrame of numeric values, say
```python
df = pd.DataFrame(np.random.random(size=(5, 3))) # a 5x3 frame of float values
```

how do you subtract the row mean from each element in the row?

In [32]:
df = pd.DataFrame(np.arange(25).reshape((5,5)))
df.apply(lambda x: x - df.mean(axis=1),axis=0)

     0    1    2    3    4
0 -2.0 -1.0  0.0  1.0  2.0
1 -2.0 -1.0  0.0  1.0  2.0
2 -2.0 -1.0  0.0  1.0  2.0
3 -2.0 -1.0  0.0  1.0  2.0
4 -2.0 -1.0  0.0  1.0  2.0

**18.** How do you count how many unique rows a DataFrame has (i.e. ignore all rows that are duplicates)? As input, use a DataFrame of zeros and ones with 10 rows and 3 columns.

```python
df = pd.DataFrame(np.random.randint(0, 2, size=(10, 3)))
```

In [33]:
df = pd.DataFrame(np.random.randint(0, 2, size=(10, 3)))

len(df.drop_duplicates(keep=False))

2

**19.** In the cell below, you have a DataFrame `df` that consists of 10 columns of floating-point numbers. Exactly 5 entries in each row are NaN values. 

For each row of the DataFrame, find the *column* which contains the *third* NaN value.

You should return a Series of column labels: `e, c, d, h, d`

In [39]:
nan = np.nan

data = [[0.04,  nan,  nan, 0.25,  nan, 0.43, 0.71, 0.51,  nan,  nan],
        [ nan,  nan,  nan, 0.04, 0.76,  nan,  nan, 0.67, 0.76, 0.16],
        [ nan,  nan, 0.5 ,  nan, 0.31, 0.4 ,  nan,  nan, 0.24, 0.01],
        [0.49,  nan,  nan, 0.62, 0.73, 0.26, 0.85,  nan,  nan,  nan],
        [ nan,  nan, 0.41,  nan, 0.05,  nan, 0.61,  nan, 0.48, 0.68]]

columns = list('abcdefghij')

df = pd.DataFrame(data, columns=columns)

(df.isnull().cumsum(axis=1)==3).idxmax(axis=1)

0    e
1    c
2    d
3    h
4    d
dtype: object

**20** Consider a DataFrame df where there is an integer column 'X':

df = pd.DataFrame({'X': [7, 2, 0, 3, 4, 2, 5, 0, 3, 4]})

For each value, count the difference back to the previous zero (or the start of the Series, whichever is closer). These values should therefore be

[1, 2, 0, 1, 2, 3, 4, 0, 1, 2]
Make this a new column 'Y'.

In [ ]:
df = pd.DataFrame({'X': [7, 2, 0, 3, 4, 2, 5, 0, 3, 4]})

df['Y'] = df.groupby((df['X'] == 0).cumsum()).cumcount()
# We're off by one before we reach the first zero.
first_zero_idx = (df['X'] == 0).idxmax()
df['Y'].iloc[0:first_zero_idx] += 1

0    0
1    1
2    0
3    1
4    2
5    3
6    4
7    0
8    1
9    2
Name: Y, dtype: int64